In [240]:
import numpy as np

In [241]:
nomes=np.array(['ana', 'rui','pedro', 'rita', 'ze', 'to', 'luis', 'joão', 'diego','gil' ])

In [242]:
nomes

array(['ana', 'rui', 'pedro', 'rita', 'ze', 'to', 'luis', 'joão', 'diego',
       'gil'], dtype='<U5')

In [243]:
pp=np.random.randint(50,101,10)

In [244]:
pp

array([ 87,  79,  77,  78, 100,  93,  71,  58,  67,  91])

In [245]:
aa=np.random.randint(150,201,10)

In [246]:
aa

array([197, 192, 199, 184, 190, 190, 199, 180, 160, 191])

In [247]:
#b

In [248]:
dados=np.array([pp,aa])

In [249]:
dados

array([[ 87,  79,  77,  78, 100,  93,  71,  58,  67,  91],
       [197, 192, 199, 184, 190, 190, 199, 180, 160, 191]])

In [250]:
imc = dados[0,:]/(dados[1,:]/100)**2
np.round(imc,1)

array([22.4, 21.4, 19.4, 23. , 27.7, 25.8, 17.9, 17.9, 26.2, 24.9])

In [251]:
np.round(imc)

array([22., 21., 19., 23., 28., 26., 18., 18., 26., 25.])

In [252]:
#c

In [253]:
nomes

array(['ana', 'rui', 'pedro', 'rita', 'ze', 'to', 'luis', 'joão', 'diego',
       'gil'], dtype='<U5')

In [254]:
imc<18.5

array([False, False, False, False, False, False,  True,  True, False,
       False])

In [255]:
imc[imc<18.5]

array([17.92884018, 17.90123457])

In [256]:
print('Pessoas com o IMC baixo: ', nomes [imc<18.5])

Pessoas com o IMC baixo:  ['luis' 'joão']


In [257]:
print('Pessoas com o IMC alto',nomes [imc>25])

Pessoas com o IMC alto ['ze' 'to' 'diego']


In [258]:
print('Pessoas com IMC ideal'), nomes [(imc>=18.6) & (imc<=25)]

Pessoas com IMC ideal


(None, array(['ana', 'rui', 'pedro', 'rita', 'gil'], dtype='<U5'))

In [259]:
print('Pessoas com o IMC baixo: ', nomes [imc<18.5])
print('Pessoas com o IMC alto',nomes [imc>25])
print('Pessoas com IMC ideal', nomes [(imc>=18.6) & (imc<=25)])

Pessoas com o IMC baixo:  ['luis' 'joão']
Pessoas com o IMC alto ['ze' 'to' 'diego']
Pessoas com IMC ideal ['ana' 'rui' 'pedro' 'rita' 'gil']


In [260]:
#d

In [261]:
i__imc__cresc=imc.argsort()

In [262]:
imc

array([22.41748048, 21.43012153, 19.44395344, 23.03875236, 27.70083102,
       25.76177285, 17.92884018, 17.90123457, 26.171875  , 24.94449165])

In [274]:

for i in i__imc__cresc:
    print ('{:>15}: pesa {} kg, mede {} cm e tem um IMC de {}.'.format(nomes[i], dados[0,i],dados[1,i],round (imc[i],1)))

           joão: pesa 58 kg, mede 180 cm e tem um IMC de 17.9.
           luis: pesa 71 kg, mede 199 cm e tem um IMC de 17.9.
          pedro: pesa 77 kg, mede 199 cm e tem um IMC de 19.4.
            rui: pesa 79 kg, mede 192 cm e tem um IMC de 21.4.
            ana: pesa 87 kg, mede 197 cm e tem um IMC de 22.4.
           rita: pesa 78 kg, mede 184 cm e tem um IMC de 23.0.
            gil: pesa 91 kg, mede 191 cm e tem um IMC de 24.9.
             to: pesa 93 kg, mede 190 cm e tem um IMC de 25.8.
          diego: pesa 67 kg, mede 160 cm e tem um IMC de 26.2.
             ze: pesa 100 kg, mede 190 cm e tem um IMC de 27.7.


In [264]:
imc[8]

26.171874999999996

In [265]:
#E

In [266]:
dados.std(axis=1)

array([12.19385091, 11.04355015])

In [267]:
print("desvio padrão dos pesos:", round (dados.std(axis=-1)[0],1))
print("desvio padrão dos alturas:", round (dados.std(axis=-1)[1],1))

desvio padrão dos pesos: 12.2
desvio padrão dos alturas: 11.0


In [ ]:
#f


In [269]:
dados[0,:].mean()

80.1

In [ ]:
dados[0,:]>dados[0,:].mean()